"""Add category images

Revision ID: 4aa25f8e23d2
Revises: 001
Create Date: 2026-04-10 20:03:25.781653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4aa25f8e23d2'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_imagens',
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('url_imagem', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('categoria')
    )
    op.create_foreign_key(None, 'produtos', 'categorias_imagens', ['categoria_produto'], ['categoria'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produtos', type_='foreignkey')
    op.drop_table('categorias_imagens')
    # ### end Alembic commands ###
