"""Add indexes for analytics performance

Revision ID: e6ccbaf57ed8
Revises: 4aa25f8e23d2
Create Date: 2026-04-13 18:47:54.045239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e6ccbaf57ed8'
down_revision: Union[str, None] = '4aa25f8e23d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avaliacoes_pedidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_avaliacoes_pedidos_id_pedido'), ['id_pedido'], unique=False)

    with op.batch_alter_table('consumidores', schema=None) as batch_op:
        batch_op.alter_column('prefixo_cep',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('nome_consumidor',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('cidade',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_consumidores_id_consumidor'), ['id_consumidor'], unique=False)

    with op.batch_alter_table('itens_pedidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_pedidos_id_produto'), ['id_produto'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens_pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_pedidos_id_produto'))

    with op.batch_alter_table('consumidores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consumidores_id_consumidor'))
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
        batch_op.alter_column('cidade',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('nome_consumidor',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('prefixo_cep',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('avaliacoes_pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avaliacoes_pedidos_id_pedido'))

    # ### end Alembic commands ###
